# Generated by Django 2.2.3 on 2019-07-31 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0012_auto_20190801_0153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='writer',
        ),
    ]
