# Generated by Django 2.2.3 on 2019-07-31 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0015_auto_20190801_0310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.CharField(default='', max_length=200),
        ),
    ]
