# Generated by Django 2.2.3 on 2019-08-04 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0017_auto_20190804_1702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
    ]
