# Generated by Django 2.2.3 on 2019-08-05 13:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0021_comment_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateField(default=datetime.date(2019, 8, 5)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='school',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
