# Generated by Django 2.2.3 on 2019-08-09 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0024_auto_20190809_1326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='File',
        ),
        migrations.CreateModel(
            name='BoardFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boardFile', models.FileField(null=True, upload_to='board/')),
                ('filename', models.CharField(default='', max_length=100)),
                ('board', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='boards', to='first.Board')),
            ],
        ),
    ]
