# Generated by Django 2.2.3 on 2019-08-04 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teamproject', '0008_auto_20190801_2025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='refFile',
        ),
    ]
