# Generated by Django 2.2.3 on 2019-08-09 04:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamproject', '0010_commenttb'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamboard',
            name='views',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='commenttb',
            name='created_date',
            field=models.DateField(default=datetime.date(2019, 8, 9)),
        ),
    ]
