# Generated by Django 2.2.3 on 2019-08-09 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teamproject', '0011_auto_20190809_1326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamboard',
            name='File',
        ),
        migrations.CreateModel(
            name='FileTb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamFile', models.FileField(null=True, upload_to='teamboard/')),
                ('filename', models.CharField(default='', max_length=100)),
                ('teamboard', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teamboards', to='teamproject.TeamBoard')),
            ],
        ),
    ]
